name: Check Gus Events

on:
  schedule:
    # Run every hour at minute 0
    - cron: "0 * * * *"
  workflow_dispatch: # Allow manual triggering

jobs:
  check-events:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Check for new gus events
        env:
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
          NOTIFICATION_EMAIL: ${{ secrets.NOTIFICATION_EMAIL }}
        run: npm run check-events

      - name: Commit updated events file
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add last_events.json
          git diff --staged --quiet || git commit -m "Update last events [skip ci]"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
